name: C/C++ CI

on:
  push:
    branches: [ testme* ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: echo no configure yet
    - name: make "CFLAGS=-Wall -DPRNG_MT -g" CC=gcc
      run: make
    - name: make test1
      run: make test1
    - name: make showcrashlogs
      run: make showcrashlogs
